development:
  first_notice: ".75"
  second_notice: ".5"
  third_notice: ".25"

test:
  first_notice: <%= ENV['CREDIT_LIMIT_FIRST_NOTICE'] %>
  second_notice: <%= ENV['CREDIT_LIMIT_SECOND_NOTICE'] %>
  third_notice: <%= ENV['CREDIT_LIMIT_THIRD_NOTICE'] %>

production:
  first_notice: <%= ENV['CREDIT_LIMIT_FIRST_NOTICE'] %>
  second_notice: <%= ENV['CREDIT_LIMIT_SECOND_NOTICE'] %>
  third_notice: <%= ENV['CREDIT_LIMIT_THIRD_NOTICE'] %>
