default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: registryadmin
  password: registryadmin

development:
  <<: *default
  database: registry_development

test:
  <<: *default
  database: registry_test

production:
  <<: *default
  database: registry
  password: <%= ENV['REGISTRY_DATABASE_PASSWORD'] %>

troy:
  adapter: postgresql
  pool: 25
  username: directuser
  password: directuser
  host: 172.16.46.83
  database: direct