development:
  url: redis://localhost:6379/12
  :concurrency: 5
  :queues:
    - internal_registry_changes
    - sync_registry_changes
    - registry_mailer

test:
  url: redis://localhost:6379/12

production:
  url: redis://localhost:6379/12