development:
  url: redis://localhost:6379/12
  :concurrency: 5
  :queues:
    - sync_registry_changes
    - registry_mailer
    - migrate_troy_dns

test:
  url: redis://localhost:6379/12

production:
  url: redis://localhost:6379/12